version: '3.8'

services:
  shadowbound:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: shadowbound
  nginx-eval:
    build:
      context: .
      dockerfile: eval/nginx/Dockerfile
    volumes:
      - ./eval/nginx/results:/results
    environment:
      - TARGET=${TARGET:-shadowbound}
    privileged: true

# docker compose up --build shadowbound
