services:
  shadowbound:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - "org.opencontainers.image.source=https://github.com/cla7aye15I4nd/shadowbound"
    image: ghcr.io/cla7aye15i4nd/shadowbound/shadowbound:1.0.0
  nginx-eval:
    build:
      context: .
      dockerfile: artifact/nginx/Dockerfile
      labels:
        - "org.opencontainers.image.source=https://github.com/cla7aye15I4nd/shadowbound"
    volumes:
      - ./artifact/nginx/results:/results
    environment:
      - TARGET=${TARGET:-shadowbound}
    privileged: true
    image: ghcr.io/cla7aye15i4nd/shadowbound/shadowbound-nginx:1.0.0
    depends_on:
      - shadowbound
  chakra-eval:
    build:
      context: .
      dockerfile: artifact/chakra/Dockerfile
      labels:
        - "org.opencontainers.image.source=https://github.com/cla7aye15I4nd/shadowbound"
    volumes:
      - ./artifact/chakra/results:/results
    privileged: true
    image: ghcr.io/cla7aye15i4nd/shadowbound/shadowbound-chakra:1.0.0
  sec-eval:
    build:
      context: artifact/security
      dockerfile: Dockerfile
      labels:
        - "org.opencontainers.image.source=https://github.com/cla7aye15I4nd/shadowbound"
    image: ghcr.io/cla7aye15i4nd/shadowbound/shadowbound-sec-eval:1.0.0
    depends_on:
      - shadowbound
  spec2017-eval:
    build:
      context: .
      dockerfile: artifact/spec2017/Dockerfile
      labels:
        - "org.opencontainers.image.source=https://github.com/cla7aye15I4nd/shadowbound"
    privileged: true
    depends_on:
      - shadowbound
