version: '3.8'

services:
  shadowbound:
    build:
      context: .
      dockerfile: Dockerfile
    image: shadowbound
  nginx-eval:
    build:
      context: .
      dockerfile: artifact/nginx/Dockerfile
    volumes:
      - ./artifact/nginx/results:/results
    environment:
      - TARGET=${TARGET:-shadowbound}
  sec-eval:
    build:
      context: artifact/security
      dockerfile: Dockerfile
    image: sec-eval
  spec2017-eval:
    build:
      context: .
      dockerfile: artifact/spec2017/Dockerfile
    image: spec2017-eval

# docker compose up --build shadowbound
# docker compose up --build nginx-eval
# docker compose up --build sec-eval
# docker compose up --build spec2017-eval
